### ISSUE TITLE
Support for StrictMode

### ISSUE THREAD

**Issue by Martizs** [maslianok/react-resize-detector#109]
Currently when trying to use this with React.StrictMode i get this error: 
'findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ResizeDetector which is inside StrictMode' .
Would really love to use StrictMode and this awesome library together.

**Comment by maslianok** [comment]
@Martizs please make sure you've read and understood this part of README https://github.com/maslianok/react-resize-detector#refs

Simply say, you have to help the library and pass some reference to the block you want to handle resizes.
Otherwise, it will use `findDOMNode` function and throw a warning in strict mode
