### ISSUE TITLE
Only detects shrinks, not expands

### ISSUE THREAD

**Issue by chrisjpatty** [maslianok/react-resize-detector#11]
Love the idea for this plugin, but I'm having trouble getting it to work predictably. I have a component like this: 
```javascript
export class Body extends Component{
  onResize = (width) => {
    console.log(width)
  }
  render(){
    const {className = "", showDrawer = false, children} = this.props;
    return(
      <div className={"body container-fluid " + className + " " + (showDrawer ? "drawer-shown " : "")}>
        <ReactResizeDetector handleWidth onResize={this.onResize} />
        {children}
      </div>
    )
  }
}
```
When I shrink the page it fires the resize event, but not when the page is expanded. Are there any requirements for the CSS of the parent element to make this work?

**Comment by bavicj** [comment]
I have the same problem. It detects only shrinking and remembers minimum size. Then when I expand the page and shrink again, it detects only shrinking for lower size as was the minimum size

**Comment by sonsoleslp** [comment]
Any updates on this issue?

**Comment by Lef-F** [comment]
Found a quick solution to this issue.
In your `componentDidMount()` function add:
`window.addEventListener('resize', this.theFunctionThatShouldBeCalledOnResize);`

and in your `componentDidUnmount()` add:
`window.removeEventListener('resize', this.theFunctionThatShouldBeCalledOnResize);`

React-resize-detector is useful if you wish to track when your 'root' `<div>` gets resized, instead of the browser window.

**Extra info:** The real problem in this issue is that react-resize-detector checks when your 'root' `<div>` gets resized. But if the `<div>` it is shorter than your window size, then changing the window height will not affect the 'root' `<div>` size, thus react-resize-detector is not triggered.

**Comment by maslianok** [comment]
Should be fixed in v.2.0.0
https://github.com/maslianok/react-resize-detector/releases/tag/2.0.0
