### ISSUE TITLE
Does not detect Chrome Developer Tools Mobile Emulation Resize

### ISSUE THREAD

**Issue by luhis** [maslianok/react-resize-detector#2]
Hi There,

I'm just having a look at your plugin, it looks great but it doesn't play quite right with the Chrome Developer tools.

In your demo I can resize the main div by switching on mobile device emulation, the div doesn't react, and the resize count remains at zero. If I click the Toggle Left Panel button, then toggle the mobile device emulation the resize count starts incrementing as it should.

I'm sure this isn't a problem in the real world, but that is the first thing I did when I opened the demo.

Thanks

**Comment by maslianok** [comment]
@luhis Thanks for reporting this and sorry for not answering for so long.

It's really weird issue. I have no idea why it happens.
`onResize` doesn't work for just mounted components. And it works as expected when you update the component.

I think it wasn't reported before just because real applications being updated right after mounting.

For now, I fixed it by putting `forceUpdate` to componentWillMount.

But we have to definitely find a better solution...
