### ISSUE TITLE
"Debounce" support?

### ISSUE THREAD

**Issue by Eric24** [maslianok/react-resize-detector#29]
Are there any plans to add support for "debounce"? Currently, when the browser is resized, the resize event fires multiple times. While that might be useful in some applications, I would rather have it only fire once or maybe twice, so that I don't unnecessarily start dozens or hundreds of components re-rendering more often than necessary.

**Comment by maslianok** [comment]
Hi @Eric24,
You can handle it on your own

```
import debounce from 'lodash/debounce';

...

constructor(props) {
  super(props);
  this.onResizeDebounced = debounce(this.onResize, 1000);
}

onResize = () => {
  // will be executed once per second
}

render() {
  ...
  <ReactResizeDetector onResize={this.onResizeDebounced} />
}

```

**Comment by maslianok** [comment]
Well, it's hard to foresee all users needs. Someone may want to trigger this event at the beginning/end and someone doesn't (leading/trailing option for [debounce](https://lodash.com/docs/4.17.5#debounce)). Someone may need [throttle](https://lodash.com/docs/4.17.5#throttle) instead of debounce etc.

That's why I prefer to keep this library simple and to not overcomplicate things by adding all this stuff for everyone... I think it's very simple to achieve what you need without integrating additional modules into the library.

Hope this explains my position. 

Anyway, thanks for your suggestion!

**Comment by maslianok** [comment]
This feature lands in v.2.2.0. 
Thanks to @lamhieu-vk :)
