### ISSUE TITLE
Handle resize if element is inside a `display: grid`

### ISSUE THREAD

**Issue by rodoabad** [maslianok/react-resize-detector#47]
Does `react-resize-detector` support CSS grids? I couldn't get `react-resize-detector` to detect resize when the element is inside a grid.

Here's a downstream issue - https://github.com/recharts/recharts/issues/1423

**Comment by maslianok** [comment]
hi @rodoabad 

To be honest, I didn't test the library with CSS grids before.
----
I created an example with styles you mentioned here recharts/recharts#1423

styles.css
```
.wrapper {
  border: 1px solid blue;
  display: grid;
  padding: 5px;
  grid-template-areas:
    'hello'
    'main';
}

.hello {
  height: 200px;
  border: 1px solid red;
  grid-area: hello;
  margin-bottom: 5px;
}

.charts {
  border: 1px solid green;
  grid-area: main;
}
```

index.js
```
<div className="wrapper">
        <div className="hello" />
        <div className="charts">
          ...

          <ResizeDetector handleWidth handleHeight onResize={this.onResize} />
        </div>
      </div>
```

and it works.

I think the problem is that Recharts uses the old version of the library.
Please, try to upgrade to the latest version.

**Comment by rodoabad** [comment]
@maslianok just saw this. Thanks! Looks like we need to update the version.
