### ISSUE TITLE
Removing "resize-detector" html element.

### ISSUE THREAD

**Issue by Fleuv** [maslianok/react-resize-detector#59]
Hello,

Is it possible to remove the `<div>` or whatever `nodeType` was specified?

**Comment by maslianok** [comment]
Hi, @Fleuv 

It's a very good question! I wanted to immediately say 'no', but now I see that we can try to remove this element... We use it only for detecting a parentElement and I think we can rewrite this logic.

Thanks for the question. I would appreciate if you can help me with this. Otherwise, I'll be able to work on this in 1-2 weeks.

**Comment by maslianok** [comment]
@Fleuv 
extra elements were removed for all render types except "Callback Pattern".
Please update to v4.
