### ISSUE TITLE
Issues with 2+ children in v4.0.5

### ISSUE THREAD

**Issue by clintharris** [maslianok/react-resize-detector#69]
I'm noticing a couple of issues with v4.0.5 and how the array of children are handled.

1. The following results in a `Each child in a list should have a unique "key" prop` warning:
```jsx
<ReactResizeDetector>
  <Foo />
  <Bar />
</ReactResizeDetector>
```
2. The following results in `TypeError: element is null`:
```jsx
<ReactResizeDetector>
  { someBoolean ? <Foo /> : null }
  <Bar />
</ReactResizeDetector>
```

**Comment by maslianok** [comment]
@clintharris thanks for reaching out!

Regarding the first issue, I'd like to force everyone to set element keys intentionally.
Of course, we can set keys inside the library but this will rewrite keys in case they set by the user.

The next example should work without any warnings
```
<ReactResizeDetector>
  <Foo key="foo" />
  <Bar key="bar" />
</ReactResizeDetector>
```

The second issue fixed in the v4.1.1
